site_name: Zeus Model Editor

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Model Editor: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
